name: sami_programming
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # Link to PR version as not currently merged
  # https://github.com/flutter/plugins/pull/1247
  #webview_flutter:
  #  git:
  #    url: git://github.com/shaqian/plugins.git
  #    path: packages/webview_flutter
  webview_flutter:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/blockly-games/
    - assets/blockly-games/en/
    - assets/blockly-games/en/bird/
    - assets/blockly-games/en/bird/generated/
    - assets/blockly-games/en/bird/generated/en/
    - assets/blockly-games/en/common/
    - assets/blockly-games/en/generated/
    - assets/blockly-games/en/generated/en/
    - assets/blockly-games/en/index/
    - assets/blockly-games/en/index/generated/
    - assets/blockly-games/en/index/generated/en/
    - assets/blockly-games/en/maze/
    - assets/blockly-games/en/maze/generated/
    - assets/blockly-games/en/maze/generated/en/
    - assets/blockly-games/en/movie/
    - assets/blockly-games/en/movie/generated/
    - assets/blockly-games/en/movie/generated/en/
    - assets/blockly-games/en/music/
    - assets/blockly-games/en/music/generated/
    - assets/blockly-games/en/music/generated/en/
    - assets/blockly-games/en/pond/
    - assets/blockly-games/en/pond/docs/
    - assets/blockly-games/en/pond/docs/generated/
    - assets/blockly-games/en/pond/docs/generated/en/
    - assets/blockly-games/en/pond/duck/
    - assets/blockly-games/en/pond/duck/generated/
    - assets/blockly-games/en/pond/duck/generated/en/
    - assets/blockly-games/en/pond/generated/
    - assets/blockly-games/en/pond/generated/en/
    - assets/blockly-games/en/pond/tutor/
    - assets/blockly-games/en/pond/tutor/generated/
    - assets/blockly-games/en/pond/tutor/generated/en/
    - assets/blockly-games/en/puzzle/
    - assets/blockly-games/en/puzzle/generated/
    - assets/blockly-games/en/puzzle/generated/en/
    - assets/blockly-games/en/third-party/
    - assets/blockly-games/en/third-party/ace/
    - assets/blockly-games/en/third-party/blockly/
    - assets/blockly-games/en/third-party/blockly/media/
    - assets/blockly-games/en/third-party/JS-Interpreter/
    - assets/blockly-games/en/third-party/midi-js-soundfonts/
    - assets/blockly-games/en/third-party/midi-js-soundfonts/banjo/
    - assets/blockly-games/en/third-party/midi-js-soundfonts/choir/
    - assets/blockly-games/en/third-party/midi-js-soundfonts/drum/
    - assets/blockly-games/en/third-party/midi-js-soundfonts/flute/
    - assets/blockly-games/en/third-party/midi-js-soundfonts/guitar/
    - assets/blockly-games/en/third-party/midi-js-soundfonts/piano/
    - assets/blockly-games/en/third-party/midi-js-soundfonts/trumpet/
    - assets/blockly-games/en/third-party/midi-js-soundfonts/violin/
    - assets/blockly-games/en/third-party/SoundJS/
    - assets/blockly-games/en/turtle/
    - assets/blockly-games/en/turtle/generated/
    - assets/blockly-games/en/turtle/generated/en/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
